//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifLk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public account()
        {
            this.character = new HashSet<character>();
        }
    
        public long ID { get; set; }
        public bool IsActive { get; set; }
        public bool IsGM { get; set; }
        public decimal SteamID { get; set; }
    
        public virtual ICollection<character> character { get; set; }
    }
}
