//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifLk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class chars_deathlog
    {
        public long ID { get; set; }
        public long Time { get; set; }
        public long CharID { get; set; }
        public long KillerID { get; set; }
        public Nullable<byte> IsKnockout { get; set; }
    }
}
