//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifLk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class character
    {
        public character()
        {
            this.character_effects = new HashSet<character_effects>();
            this.character_titles = new HashSet<character_titles>();
            this.skills = new HashSet<skills>();
            this.equipment_slots = new HashSet<equipment_slots>();
            this.guild_actions_processed = new HashSet<guild_actions_processed>();
            this.guild_actions_queue = new HashSet<guild_actions_queue>();
            this.guild_actions_queue1 = new HashSet<guild_actions_queue>();
            this.personal_lands = new HashSet<personal_lands>();
        }
    
        public long ID { get; set; }
        public byte IsActive { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public Nullable<long> GeoID { get; set; }
        public long AccountID { get; set; }
        public Nullable<int> GeoAlt { get; set; }
        public byte RaceID { get; set; }
        public int Alignment { get; set; }
        public long CriminalSecondsLeft { get; set; }
        public long Strength { get; set; }
        public sbyte StrengthLock { get; set; }
        public long Agility { get; set; }
        public sbyte AgilityLock { get; set; }
        public long Intellect { get; set; }
        public sbyte IntellectLock { get; set; }
        public long Willpower { get; set; }
        public sbyte WillpowerLock { get; set; }
        public long Constitution { get; set; }
        public sbyte ConstitutionLock { get; set; }
        public long RootContainerID { get; set; }
        public long EquipmentContainerID { get; set; }
        public int HardHP { get; set; }
        public int HardStam { get; set; }
        public int SoftHP { get; set; }
        public int SoftStam { get; set; }
        public long Luck { get; set; }
        public long HungerRate { get; set; }
        public byte[] AlchemyHash { get; set; }
        public byte[] VisibilityHash { get; set; }
        public byte[] appearance { get; set; }
        public Nullable<long> GuildID { get; set; }
        public Nullable<byte> GuildRoleID { get; set; }
        public Nullable<long> TitleMessageID { get; set; }
        public Nullable<long> BindedObjectID { get; set; }
        public Nullable<long> RallyObjectID { get; set; }
        public long LastTimeUsedPraiseYourGodAbility { get; set; }
        public long LastTimeUsedTransmuteIntoGold { get; set; }
        public System.DateTime CreateTimestamp { get; set; }
        public Nullable<System.DateTime> DeleteTimestamp { get; set; }
    
        public virtual account account { get; set; }
        public virtual ICollection<character_effects> character_effects { get; set; }
        public virtual containers containers { get; set; }
        public virtual guild_roles guild_roles { get; set; }
        public virtual race race { get; set; }
        public virtual ICollection<character_titles> character_titles { get; set; }
        public virtual ICollection<skills> skills { get; set; }
        public virtual ICollection<equipment_slots> equipment_slots { get; set; }
        public virtual ICollection<guild_actions_processed> guild_actions_processed { get; set; }
        public virtual ICollection<guild_actions_queue> guild_actions_queue { get; set; }
        public virtual ICollection<guild_actions_queue> guild_actions_queue1 { get; set; }
        public virtual ICollection<personal_lands> personal_lands { get; set; }
        public virtual guilds guilds { get; set; }
        public virtual containers containers1 { get; set; }
    }
}
