//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifLk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class character_effects
    {
        public long ID { get; set; }
        public byte PlayerEffectID { get; set; }
        public long CharacterID { get; set; }
        public long Magnitude { get; set; }
        public long DurationLeft { get; set; }
    
        public virtual character character { get; set; }
    }
}
