//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifLk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class claims
    {
        public long ID { get; set; }
        public Nullable<long> GuildLandID { get; set; }
        public Nullable<long> PersonalLandID { get; set; }
        public int SupportPoints { get; set; }
    
        public virtual guild_lands guild_lands { get; set; }
        public virtual personal_lands personal_lands { get; set; }
    }
}
