//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifLk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class containers
    {
        public containers()
        {
            this.character = new HashSet<character>();
            this.character1 = new HashSet<character>();
            this.items = new HashSet<items>();
            this.containers1 = new HashSet<containers>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ParentID { get; set; }
        public long ObjectTypeID { get; set; }
        public byte Quality { get; set; }
        public Nullable<long> FeatureID { get; set; }
    
        public virtual ICollection<character> character { get; set; }
        public virtual ICollection<character> character1 { get; set; }
        public virtual objects_types objects_types { get; set; }
        public virtual features features { get; set; }
        public virtual ICollection<items> items { get; set; }
        public virtual ICollection<containers> containers1 { get; set; }
        public virtual containers containers2 { get; set; }
    }
}
