//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifLk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class effects_sets
    {
        public long ID { get; set; }
        public byte EffectID1 { get; set; }
        public Nullable<byte> EffectID2 { get; set; }
        public byte EffectID3 { get; set; }
    
        public virtual effects effects { get; set; }
        public virtual effects effects1 { get; set; }
        public virtual effects effects2 { get; set; }
    }
}
