//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifLk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class effects
    {
        public effects()
        {
            this.effects_sets = new HashSet<effects_sets>();
            this.effects_sets1 = new HashSet<effects_sets>();
            this.effects_sets2 = new HashSet<effects_sets>();
            this.item_effects = new HashSet<item_effects>();
        }
    
        public byte ID { get; set; }
        public string Effect_name { get; set; }
        public Nullable<long> ResultPreparationID { get; set; }
        public Nullable<long> ResultPotionID { get; set; }
        public Nullable<byte> PlayerEffectID { get; set; }
    
        public virtual objects_types objects_types { get; set; }
        public virtual objects_types objects_types1 { get; set; }
        public virtual ICollection<effects_sets> effects_sets { get; set; }
        public virtual ICollection<effects_sets> effects_sets1 { get; set; }
        public virtual ICollection<effects_sets> effects_sets2 { get; set; }
        public virtual ICollection<item_effects> item_effects { get; set; }
    }
}
