//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifLk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class equipment_slots
    {
        public long ID { get; set; }
        public long CharacterID { get; set; }
        public byte Slot { get; set; }
        public Nullable<long> ItemID { get; set; }
    
        public virtual character character { get; set; }
        public virtual items items { get; set; }
    }
}
