//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifLk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class guild_standing_types
    {
        public guild_standing_types()
        {
            this.guild_actions_queue = new HashSet<guild_actions_queue>();
            this.guild_standings = new HashSet<guild_standings>();
        }
    
        public byte ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<guild_actions_queue> guild_actions_queue { get; set; }
        public virtual ICollection<guild_standings> guild_standings { get; set; }
    }
}
