//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifLk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class guilds
    {
        public guilds()
        {
            this.character = new HashSet<character>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public byte GuildTypeID { get; set; }
        public byte IsActive { get; set; }
        public string GuildCharter { get; set; }
        public string GuildTag { get; set; }
        public System.DateTime CreateTimestamp { get; set; }
        public Nullable<System.DateTime> DeleteTimestamp { get; set; }
    
        public virtual ICollection<character> character { get; set; }
        public virtual guild_types guild_types { get; set; }
    }
}
