//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifLk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class guild_actions_processed
    {
        public long ID { get; set; }
        public decimal TicketID { get; set; }
        public string ActionType { get; set; }
        public string ProcessedStatus { get; set; }
        public Nullable<long> ProducerCharID { get; set; }
        public Nullable<long> ProducerCharDeletedID { get; set; }
        public Nullable<long> GuildID { get; set; }
        public Nullable<long> GuildDeletedID { get; set; }
        public Nullable<long> CharID { get; set; }
        public Nullable<long> CharDeletedID { get; set; }
        public string GuildName { get; set; }
        public string GuildTag { get; set; }
        public string GuildCharter { get; set; }
        public Nullable<byte> GuildTypeID { get; set; }
        public byte CharIsKicked { get; set; }
        public Nullable<byte> CharGuildRoleID { get; set; }
        public Nullable<long> OtherGuildID { get; set; }
        public Nullable<long> OtherGuildDeletedID { get; set; }
        public Nullable<byte> StandingTypeID { get; set; }
        public System.DateTime ProcessedTimestamp { get; set; }
    
        public virtual character character { get; set; }
    }
}
