//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifLk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class guild_lands
    {
        public guild_lands()
        {
            this.claims = new HashSet<claims>();
        }
    
        public long ID { get; set; }
        public long GuildID { get; set; }
        public string Name { get; set; }
        public long CenterGeoID { get; set; }
        public long Radius { get; set; }
        public long LandType { get; set; }
    
        public virtual ICollection<claims> claims { get; set; }
        public virtual guilds guilds { get; set; }
    }
}
