//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifLk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class guild_standings
    {
        public long ID { get; set; }
        public long GuildID1 { get; set; }
        public long GuildID2 { get; set; }
        public byte StandingTypeID { get; set; }
    
        public virtual guild_standing_types guild_standing_types { get; set; }
        public virtual guilds guilds { get; set; }
        public virtual guilds guilds1 { get; set; }
    }
}
