//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifLk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class guilds
    {
        public guilds()
        {
            this.character = new HashSet<character>();
            this.guild_actions_queue = new HashSet<guild_actions_queue>();
            this.guild_actions_queue1 = new HashSet<guild_actions_queue>();
            this.guild_lands = new HashSet<guild_lands>();
            this.guild_standings = new HashSet<guild_standings>();
            this.guild_standings1 = new HashSet<guild_standings>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public byte GuildTypeID { get; set; }
        public byte IsActive { get; set; }
        public string GuildCharter { get; set; }
        public string GuildTag { get; set; }
        public System.DateTime CreateTimestamp { get; set; }
        public Nullable<System.DateTime> DeleteTimestamp { get; set; }
    
        public virtual ICollection<character> character { get; set; }
        public virtual ICollection<guild_actions_queue> guild_actions_queue { get; set; }
        public virtual ICollection<guild_actions_queue> guild_actions_queue1 { get; set; }
        public virtual ICollection<guild_lands> guild_lands { get; set; }
        public virtual ICollection<guild_standings> guild_standings { get; set; }
        public virtual ICollection<guild_standings> guild_standings1 { get; set; }
        public virtual guild_types guild_types { get; set; }
    }
}
