//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifLk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_effects
    {
        public long ID { get; set; }
        public long ItemID { get; set; }
        public byte EffectID { get; set; }
        public int Magnitude { get; set; }
    
        public virtual effects effects { get; set; }
        public virtual items items { get; set; }
    }
}
