//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifLk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lifdscp_online_history
    {
        public decimal ID { get; set; }
        public long CharacterID { get; set; }
        public System.DateTime LoggedInAt { get; set; }
        public System.DateTime LoggedOutAt { get; set; }
        public bool IsLoggedOut { get; set; }
    }
}
