//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifLk.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LifDB : DbContext
    {
        public LifDB()
            : base("name=LifDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
            Database.SetInitializer<LifDB>(null);
        }
    
        public virtual DbSet<account> account { get; set; }
        public virtual DbSet<character> character { get; set; }
        public virtual DbSet<containers> containers { get; set; }
        public virtual DbSet<custom_texts> custom_texts { get; set; }
        public virtual DbSet<equipment_slots> equipment_slots { get; set; }
        public virtual DbSet<features> features { get; set; }
        public virtual DbSet<guild_roles> guild_roles { get; set; }
        public virtual DbSet<guild_type_role_msgs> guild_type_role_msgs { get; set; }
        public virtual DbSet<guild_types> guild_types { get; set; }
        public virtual DbSet<guilds> guilds { get; set; }
        public virtual DbSet<items> items { get; set; }
        public virtual DbSet<objects_types> objects_types { get; set; }
        public virtual DbSet<prices> prices { get; set; }
        public virtual DbSet<titles> titles { get; set; }
    }
}
