//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifLk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class objects_types
    {
        public objects_types()
        {
            this.containers = new HashSet<containers>();
            this.effects = new HashSet<effects>();
            this.effects1 = new HashSet<effects>();
            this.items = new HashSet<items>();
            this.prices = new HashSet<prices>();
            this.objects_types1 = new HashSet<objects_types>();
        }
    
        public long ID { get; set; }
        public Nullable<long> ParentID { get; set; }
        public string Name { get; set; }
        public bool IsContainer { get; set; }
        public bool IsMovableObject { get; set; }
        public bool IsUnmovableobject { get; set; }
        public bool IsTool { get; set; }
        public bool IsDevice { get; set; }
        public bool IsDoor { get; set; }
        public Nullable<long> MaxContSize { get; set; }
        public Nullable<byte> Length { get; set; }
        public Nullable<long> MaxStackSize { get; set; }
        public Nullable<long> UnitWeight { get; set; }
        public string BackgndImage { get; set; }
        public Nullable<int> WorkAreaTop { get; set; }
        public Nullable<int> WorkAreaLeft { get; set; }
        public Nullable<int> WorkAreaWidth { get; set; }
        public Nullable<int> WorkAreaHeight { get; set; }
        public Nullable<int> BtnCloseTop { get; set; }
        public Nullable<int> BtnCloseLeft { get; set; }
        public string FaceImage { get; set; }
        public string Description { get; set; }
        public Nullable<long> BasePrice { get; set; }
        public Nullable<long> OwnerTimeout { get; set; }
    
        public virtual ICollection<containers> containers { get; set; }
        public virtual ICollection<effects> effects { get; set; }
        public virtual ICollection<effects> effects1 { get; set; }
        public virtual ICollection<items> items { get; set; }
        public virtual ICollection<prices> prices { get; set; }
        public virtual ICollection<objects_types> objects_types1 { get; set; }
        public virtual objects_types objects_types2 { get; set; }
    }
}
