//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LifLk.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill_type
    {
        public skill_type()
        {
            this.skills = new HashSet<skills>();
            this.skill_type1 = new HashSet<skill_type>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<long> Parent { get; set; }
        public Nullable<byte> Group { get; set; }
        public string PrimaryStat { get; set; }
        public string SecondaryStat { get; set; }
        public Nullable<long> MasterMessageID { get; set; }
        public Nullable<long> GMMessageID { get; set; }
    
        public virtual ICollection<skills> skills { get; set; }
        public virtual ICollection<skill_type> skill_type1 { get; set; }
        public virtual skill_type skill_type2 { get; set; }
    }
}
